---

# See https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-an-organization--fine-grained-access-tokens
- name: "{{ item.repo_name }} | Get GitHub Runner Token"
  shell: |
    curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer {{ item.api_token | default(operations_github_api_token) }}" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/{{item.repo_name}}/actions/runners/registration-token
  register: result
  failed_when:
    - "'token' not in result.stdout"
- set_fact:
    github_runner_registration_token:  "{{ result.stdout | from_json }}"

- debug:
    msg: "API response: {{ github_runner_registration_token }}"
  failed_when:
    - "'token' not in github_runner_registration_token"

- name: "{{ item.repo_name }} | Setup GitHub Runner"
  shell:
    cmd: "cd {{ operations_github_runner_path }} && ./config.sh remove --token {{ github_runner_registration_token.token }} && ./config.sh --replace --unattended --url {{ item.repo_host | default('https://github.com') }}/{{ item.repo_name }} --token {{ github_runner_registration_token.token }} --name {{ item.runner_name }} --labels {{ item.runner_labels }}"
    chdir: "{{ operations_github_runner_path }}"
  become: true
  become_user: "{{ item.user }}"

#- name: Add GitHub Runner Service
#  shell:
#    cmd: "cd {{ operations_github_runner_path }} && ./config.sh remove --token {{ item.runner_token }} && ./config.sh --unattended --url {{ item.repo_url }} --token {{ item.runner_token }} --name {{ item.runner_name }} --labels {{ item.runner_labels }}"
#    chdir: "{{ operations_github_runner_path }}"
#  become: true
#  become_user: "{{ item.user }}"
#  with_items: "{{ operations_github_runners }}"
