---

# See Your repo > Settings > Actions > Runner > New Runner
- name: Download the Runner
  shell:
    cmd: |
      mkdir {{ github_runner_path }} -p
      cd {{ github_runner_path }}
      curl --fail -o {{ github_runner_path }}/{{ github_runner_download_filename }} -L {{ github_runner_download_url }}
      tar xzf {{ github_runner_download_filename }}
      ./bin/installdependencies.sh
      chown {{ github_runner_user }}:{{ github_runner_user }} . -R
    creates: "{{ github_runner_path }}/config.sh"

- name: Verify runner
  file:
    path: "{{ github_runner_path }}"
    state: directory
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"

- name: Create Sites directory
  file:
    state: directory
    dest: "{{ github_runner_site_symlink_directory }}"
    force: yes
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"

- name: Create site symlink
  file:
    state: link
    dest: "{{ github_runner_site_symlink_directory }}"
    src: "{{ github_runner_path }}/_work/{{ github_runner_repo | split('/') | last }}/{{ github_runner_repo | split('/') | last }}"
    force: yes
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"

- name: Configure GitHub Runner
  include_tasks: github.yml
  with_items:
  - runner_repo: "{{ github_runner_repo }}"
    runner_user: "{{ github_runner_user }}"
    runner_name: "{{ inventory_hostname }}"
    runner_path: "{{ github_runner_path }}"
    api_token: "{{ github_runner_api_token }}"
#    runner_labels: "{{ inventory_hostname }}"


#
#- name: Configure GitHub Runners
#  include_tasks: github.yml
#  with_items: "{{ operations_github_runners }}"
