---

# See Your repo > Settings > Actions > Runner > New Runner
- name: Download the Runner
  shell:
    cmd: |
      mkdir {{ github_runner_path }} -p
      cd {{ github_runner_path }}
      curl -o {{ github_runner_path }}/{{ github_runner_download_filename }} -L https://github.com/actions/runner/releases/download/{{ github_runner_download_version }}/{{ github_runner_download_filename }}
      tar xzf {{ github_runner_path }}/{{ github_runner_download_filename }}
      ./bin/installdependencies.sh
      chown {{ github_runner_user }}:{{ github_runner_user }} . -R
    creates: "{{ github_runner_path }}/config.sh"

- name: Verify runner
  file:
    path: "{{ github_runner_path }}"
    state: directory
    owner: "{{ github_runner_user }}"
    group: "{{ github_runner_user }}"

- name: Create Sites directory
  file:
    state: directory
    dest: "{{ github_runner_site_symlink_directory }}"
    force: yes

- name: Create site symlink
  file:
    state: link
    dest: "{{ github_runner_site_symlink_directory }}"
    src: "{{ github_runner_path }}/_work/{{ github_runner_repo }}"
    force: yes


#
#- name: Configure GitHub Runners
#  include_tasks: github.yml
#  with_items: "{{ operations_github_runners }}"
