---

# See Your repo > Settings > Actions > Runner > New Runner
- name: Install GitHub Runner Software
  shell:
    cmd: |
      mkdir {{ operations_github_runner_path }} -p
      curl -o {{ operations_github_runner_path }}/actions-runner-linux-x64-2.314.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.314.1/actions-runner-linux-x64-2.314.1.tar.gz
      cd {{ operations_github_runner_path }} && tar xzf {{ operations_github_runner_path }}/actions-runner-linux-x64-2.314.1.tar.gz
      cd {{ operations_github_runner_path }} && ./bin/installdependencies.sh
      chown {{ operations_platform_user }}:{{ operations_platform_user }} {{ operations_github_runner_path }} -R
      cd {{ operations_github_runner_path }} && ./bin/installdependencies.sh
      ls -la {{ operations_github_runner_path }}
    creates: "{{ operations_github_runner_path }}"

- name: Configure GitHub Runners
  include_tasks: github.yml
  with_items: "{{ operations_github_runners }}"
