# For testing and development.

---
services:
  ash:
    image: geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest
    hostname: ${DOCKER_HOSTNAME:-ash.local.computer}
    cgroup: host
    cgroup_parent: docker.slice
    privileged: true
    volumes:
      - ./:/usr/share/ash
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./ansible:/etc/ansible
    environment:
      - ASH_OPS=yes
    build: ./
