
---
- name: Configure Server
  hosts: all
  vars_files: playbook.vars.yml
  become: true

  roles:
    - role: geerlingguy.security
      tags: system
      vars:
        security_sudoers_passwordless: "{{ ['control'] + operations_admin_users }}"

    - role: geerlingguy.github-users
      tags: system

- name: "Configure Hosting: DDEV"
  hosts: operations_host_ddev
  vars_files: playbook.vars.yml

  roles:
    - role: geerlingguy.php
      tags: system
      vars:
        php_packages_extra:
          - php-json

    - role: geerlingguy.composer
      tags: system

    - role: geerlingguy.docker
      tags: system

    - role: operations.users
      tags: operations

    - role: operations.ddev
      tags: operations, ddev

    - role: operations.runner
      tags:
      - operations
      - runner
