
---
- hosts: ash_managed
  vars_files: playbook.vars.yml
  become: true

  roles:
    - role: ash.users
      tags: ash

    - role: geerlingguy.security
      tags: system
      vars:
        security_sudoers_passwordless: "{{ ['control'] + ash_admin_users }}"

    - role: geerlingguy.github-users
      tags: system

- hosts: ash_host
  vars_files: playbook.vars.yml

  roles:
    - role: geerlingguy.php
      tags: system
      vars:
        php_packages_extra:
          - php-json

    - role: geerlingguy.composer
      tags: system

    - role: geerlingguy.docker
      tags: system

    - role: ash.ddev
      tags: ash, ddev

#    - role: ash.runner
#      tags: ash
