
---
- name: Configure Server
  hosts: servers
  become: true

  roles:
    - role: geerlingguy.security
      tags:
        - system
        - security
      vars:
        security_sudoers_passwordless: "{{ [operations_control_user|default('control')] + operations_admin_users|default([]) }}"
        security_ssh_allowed_users: "{{ [operations_control_user|default('control')] + [operations_platform_user|default('platform')] + operations_admin_users|default([]) }}"

    - role: geerlingguy.github-users
      tags:
        - system
        - security
      vars:
        github_users: "{{ operations_admin_users | default([]) }}"

- name: Configure Runner Server
  hosts: runners
  become: true

  roles:
    - role: geerlingguy.docker
      tags:
        - system
        - docker

    - role: operations.users
      tags:
        - system
        - users
        - operations

    - role: operations.ddev
      tags:
        - system
        - ddev
        - operations


- name: Setup Sites
  hosts: sites
  become: true
  roles:
    - role: operations.runner
