#
# Use a host_vars file to save server-specific variables.
# Copy this file to one named after the server FQDN.

# Add users. For each 'operations_admin_users':
# - Create a system user with sudo privileges.
# - Add all of the users's Github SSH keys to authorized_keys.
#
# WARNING: Change this, unless you want to give me access to your server.
#
operations_admin_users:
  - jonpugh

operations_github_api_token: DefaultApiToken
operations_github_runners:
  - repo_name: jonpugh/operations
    repo_host: https://github.com
    runner_name: "{{ inventory_hostname }}"
    # Set a runner-specific api_token, if desired.
    api_token: "{{ operations_github_api_token }}"
    runner_labels: "example,local,operations,{{ inventory_hostname }}"
    user: platform
