---

- name: Create Platform group
  group:
    name: "{{ ash_platform_user }}"
    state: present
    gid: "{{ ash_platform_user_gid | default(omit) }}"

- name: Create Platform user
  user:
    name: "{{ ash_platform_user }}"
    group: "{{ ash_platform_user }}"
    home: "{{ ash_platform_home }}"
    uid: "{{ ash_platform_user_uid | default(omit) }}"
    shell: /bin/bash
    system: true
    generate_ssh_key: true
    groups: docker

- name: Create Platform home directory
  file:
    state: directory
    path: "{{ ash_platform_home }}"
    group: "{{ ash_platform_user }}"
    owner: "{{ ash_platform_user }}"

- name: Create Control group
  group:
    name: "{{ ash_control_user }}"
    state: present
    gid: "{{ ash_control_user_gid | default(omit) }}"

- name: Create Control user
  user:
    name: "{{ ash_control_user }}"
    group: "{{ ash_control_user }}"
    groups: docker
    home: "{{ ash_control_home }}"
    uid: "{{ ash_control_user_uid | default(omit) }}"
    shell: /bin/bash
    system: true
    generate_ssh_key: true

- name: Create Control home directory
  file:
    state: directory
    path: "{{ ash_control_home }}"
    group: "{{ ash_control_user }}"
    owner: "{{ ash_control_user }}"
