operations_github_runner_path: /usr/share/github-runner
operations_github_api_token: DefaultApiToken
operations_github_runners:
  - repo_name: operations-project/site-runner
    # Set repo_host if using enterprise github.
    # repo_host: https://github.com
    runner_name: "{{ inventory_hostname }}"
    # Set a runner-specific api_token, if desired.
    # api_token: "{{ operations_github_api_token }}"
    runner_labels: "example,local,operations,{{ inventory_hostname }}"
    runner_user: platform
