---
- name: Install ddev
  shell: "curl -fsSL https://ddev.com/install.sh | bash"
  become: true
  become_user: "{{ operations_control_user }}"

# See https://ddev.readthedocs.io/en/latest/users/topics/hosting/
- name: Configure ddev for hosting
  command: ddev config global --router-bind-all-interfaces --omit-containers=ddev-ssh-agent --use-hardened-images --use-letsencrypt --letsencrypt-email=you@example.com`
  args:
    chdir:  "{{ operations_platform_home }}"
  become: true
  become_user: "{{ operations_platform_user }}"

- name: Confirm ddev install
  command: /usr/local/bin/ddev version
  args:
    chdir:  "{{ operations_platform_home }}"
  become: true
  become_user: "{{ operations_platform_user }}"
