---
- name: Install ddev
  shell: "curl -fsSL https://ddev.com/install.sh | bash"
  become: true
  become_user: "{{ operations_control_user }}"

- command: pwd
  args:
    chdir:  "{{ operations_platform_home }}"
  become: true
  become_user: "{{ operations_platform_user }}"

- name: Confirm ddev install
  command: /usr/local/bin/ddev version
  args:
    chdir:  "{{ operations_platform_home }}"
  become: true
  become_user: "{{ operations_platform_user }}"
