---
- name: Install ddev
  shell: "curl -fsSL https://ddev.com/install.sh | bash"
  become: true
  become_user: "{{ operations_control_user }}"

- name: Confirm ddev install
  command: /usr/local/bin/ddev version
  args:
    chdir:  "{{ operations_platform_home }}"
  become: true
  become_user: "{{ operations_platform_user }}"

# See https://ddev.readthedocs.io/en/latest/users/topics/hosting/
- name: Configure ddev for hosting
  command: "{{ operations_ddev_config_hosting_command }}"
  args:
    chdir:  "{{ operations_platform_home }}"
  become: true
  become_user: "{{ operations_platform_user }}"
