on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    env:
      PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter

    steps:
      - uses: actions/checkout@v3
        with:
          show-progress: false

      - uses: php-actions/composer@v6

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.24.0'

      - name: Information
        run: |
          docker-compose --version

      # github.ref_name is the branch name on branch builds.
      # On PRs ref_name is `PR#/merge`.
      - name: Set runner name
        if: github.event_name != 'pull_request'
        run: echo "ASH_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"

      - name: Set runner name
        if: github.event_name == 'pull_request'
        run: echo "ASH_NAME=pr${{ github.event.number }}" >> "$GITHUB_ENV"

      - name: Set variables
        run: |
          echo "ash_github_runners:
          - repo_url: ${{ github.repositoryUrl }}
            runner_token: ${{ secrets.RUNNER_TOKEN }}
            runner_name:  ${{ env.ASH_NAME }}
            runner_labels: ci,ash
            user: platform
          " > vars.ci.yml
          cat vars.ci.yml

      - name: Build Platform
        run: composer dev:start -- --extra-vars=@/usr/share/ash/vars.ci.yml
