on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    env:
      PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter

    strategy:
      matrix:
        - name: pr${{ github.event.number }}
          token: ${{ secrets.RUNNER_TOKEN }}
          repo_url: ${{ github.repositoryUrl }}
          environment: test

    steps:
      - uses: actions/checkout@v3
        with:
          show-progress: false

      - uses: php-actions/composer@v6

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.24.0'

      - name: Information
        run: |
          docker-compose --version

      - name: Set variables
        run: |
          echo "ash_github_runners:
          - repo_url: ${{ matrix.repo_url }}
            runner_token: ${{ matrix.token }}
            runner_name:  "ash.${{ matrix.name }}"
            runner_labels: ci,ash,${{ matrix.environment }}"
            user: platform
          " > vars.ci.yml
          cat vars.ci.yml

      - name: Build Platform
        run: composer dev:start -- --extra-vars=@/usr/share/ash/vars.ci.yml
