on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    env:
      PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "8.1"

    steps:
      - uses: actions/checkout@v3
        with:
          show-progress: false

      - uses: php-actions/composer@v6

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.24.0'

      - name: Information
        run: |
          docker-compose --version

      - name: Build Platform
        run: composer dev:start -- --extra-vars=@/usr/share/ash/vars.ci.yml
