on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    env:
      PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "8.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: playbook.yml
          inventory: hosts.example
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
